# Settings.yml
---
conf.py:
  ##==========================================
  ## define configuration data for conf.py as
  ## "parameter: value" pairs here:
  ##------------------------------------------
  todo_include_todos: False
  copyright: since 2013
  project: The docs-typo3-org resources
  version: 0.1
  release: 0.1.0
...
